packageExtensions:
  "@astrojs/language-server@*":
    dependencies:
      vscode-languageserver-types: "*"
      vscode-uri: "*"
  "@babel/plugin-transform-react-jsx@*":
    dependencies:
      "@babel/core": "*"
  astro@*:
    dependencies:
      fast-glob: "*"

yarnPath: .yarn/releases/yarn-sources.cjs

pnpEnableExperimentalEsm: true